"""Core domain value objects.

These Pydantic models are the contracts exchanged between subsystems and
are the single source of truth for the API schemas, the agent tool
signatures and the provenance payloads.

Design rules enforced here:

* Every assertion carries an :class:`AssertionClass` so observed fact,
  inference and recommendation are never conflated.
* Evidence is content-addressed: the payload lives off-chain, the
  ``evidence_hash`` is what the ledger commits to.
* Risk results are structured, explained and carry uncertainty.
* No model stores real patient identifiers; patient context is synthetic
  and explicitly labelled as such.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, computed_field, field_validator

from backend.app.domain.enums import (
    AcuityLevel,
    AgentRole,
    AgentRunStatus,
    ApprovalStatus,
    AssertionClass,
    AttackType,
    CriticalityTier,
    DetectorKind,
    DeviceOperationalState,
    DeviceType,
    EventKind,
    EvidenceKind,
    ImpactClass,
    IncidentState,
    NetworkState,
    PatientDependencyLevel,
    PolicyDecision,
    ProvenanceEventType,
    RecoveryOutcome,
    ResponseActionType,
    ResponseState,
    RiskBand,
    Severity,
)
from backend.app.domain.ids import canonical_hash


class DomainModel(BaseModel):
    """Base class: strict, immutable-by-convention domain objects."""

    model_config = ConfigDict(
        extra="forbid",
        use_enum_values=False,
        validate_assignment=True,
        ser_json_timedelta="float",
    )


# ===========================================================================
# Devices, patients and clinical profile
# ===========================================================================
class SyntheticPatientContext(DomainModel):
    """Synthetic patient dependency context.

    SAFETY: every field here is generated by the simulator. No real patient
    identifiers, records or PHI are present or supported anywhere in this
    platform.
    """

    synthetic: Literal[True] = True
    patient_ref: str = Field(description="Synthetic opaque reference, e.g. 'SYN-PT-001'")
    acuity: AcuityLevel = AcuityLevel.STABLE
    dependency: PatientDependencyLevel = PatientDependencyLevel.NONE
    on_life_support: bool = False
    clinician_present: bool = True
    # Minutes of device interruption judged clinically tolerable in the
    # simulation. Drives the clinical-risk term; never a clinical guideline.
    tolerable_interruption_minutes: float = Field(default=30.0, ge=0.0)

    @field_validator("patient_ref")
    @classmethod
    def _must_be_synthetic_ref(cls, v: str) -> str:
        if not v.upper().startswith("SYN-"):
            raise ValueError("patient_ref must be a synthetic reference prefixed 'SYN-'")
        return v


class DeviceProfile(DomainModel):
    """Static clinical/technical profile of an IoMT asset."""

    device_id: str
    device_type: DeviceType
    model_name: str = "simulated"
    ward: str = "ICU-1"
    criticality: CriticalityTier = CriticalityTier.CLINICALLY_SIGNIFICANT
    life_support_relevant: bool = False
    has_redundant_peer: bool = False
    redundant_peer_id: str | None = None
    supports_safe_failover: bool = False
    # Interruption the device class can absorb with no clinical consequence.
    acceptable_interruption_seconds: float = Field(default=300.0, ge=0.0)
    network_segment: str = "vlan-clinical"
    ip_address: str = "10.0.0.1"
    mac_address: str = "00:00:00:00:00:00"
    firmware_version: str = "1.0.0"
    patient: SyntheticPatientContext | None = None


class DeviceState(DomainModel):
    """Live mutable state of a simulated device."""

    device_id: str
    timestamp: datetime
    operational_state: DeviceOperationalState = DeviceOperationalState.ACTIVE
    network_state: NetworkState = NetworkState.NORMAL
    delivering_therapy: bool = False
    alarm_active: bool = False
    alarm_reason: str | None = None
    fault_codes: list[str] = Field(default_factory=list)
    service_available: bool = True
    uptime_seconds: float = 0.0
    last_command_accepted: str | None = None
    active_sessions: int = 0
    credentials_version: int = 1
    # Set by the response orchestrator so recovery can detect side effects.
    therapy_interrupted_seconds: float = 0.0


# ===========================================================================
# Events and telemetry
# ===========================================================================
class NormalisedEvent(DomainModel):
    """A single normalised event from the event/telemetry layer.

    One schema for telemetry, network flows, device state, commands, auth and
    security logs, so the detection pipeline and the benchmark-dataset
    loaders can share feature extraction.
    """

    event_id: str
    timestamp: datetime
    kind: EventKind
    device_id: str | None = None
    source_ip: str | None = None
    destination_ip: str | None = None
    source_mac: str | None = None
    protocol: str | None = None
    source_port: int | None = None
    destination_port: int | None = None
    # Numeric measurements: telemetry vitals, flow statistics, counters.
    measurements: dict[str, float] = Field(default_factory=dict)
    # Categorical / textual attributes: command names, auth results, flags.
    attributes: dict[str, str] = Field(default_factory=dict)
    # Simulator ground truth. Present ONLY for simulator- or dataset-sourced
    # events and never consumed by detection at inference time; used solely
    # for supervised training and evaluation.
    ground_truth_attack: AttackType | None = None
    ground_truth_is_attack: bool | None = None
    scenario_id: str | None = None

    def feature_view(self) -> dict[str, float | str | None]:
        """Flat view for feature extraction, excluding ground-truth labels."""
        out: dict[str, float | str | None] = {
            "kind": self.kind.value,
            "device_id": self.device_id,
            "protocol": self.protocol,
            "source_port": float(self.source_port) if self.source_port is not None else None,
            "destination_port": (
                float(self.destination_port) if self.destination_port is not None else None
            ),
        }
        for k, v in self.measurements.items():
            out[f"m_{k}"] = v
        for k, v in self.attributes.items():
            out[f"a_{k}"] = v
        return out


# ===========================================================================
# Evidence
# ===========================================================================
class EvidenceRef(DomainModel):
    """Content-addressed evidence reference.

    The payload is kept off-chain (``payload`` here, persisted in the
    evidence store). Only ``evidence_hash`` plus metadata is committed to
    the permissioned ledger, which is what keeps raw telemetry and
    synthetic patient context off the blockchain.
    """

    evidence_id: str
    kind: EvidenceKind
    created_at: datetime
    assertion_class: AssertionClass = AssertionClass.OBSERVED_FACT
    produced_by: str = Field(description="Subsystem or agent that produced this evidence")
    summary: str = ""
    event_ids: list[str] = Field(default_factory=list)
    payload: dict[str, Any] = Field(default_factory=dict)
    evidence_hash: str = ""

    def with_hash(self) -> EvidenceRef:
        """Return a copy with ``evidence_hash`` computed over the payload."""
        digest = canonical_hash(
            {
                "evidence_id": self.evidence_id,
                "kind": self.kind.value,
                "event_ids": sorted(self.event_ids),
                "payload": self.payload,
            }
        )
        return self.model_copy(update={"evidence_hash": digest})

    def verify(self) -> bool:
        """Re-derive the digest and compare. Backs ``verifyEvidence``."""
        return bool(self.evidence_hash) and self.with_hash().evidence_hash == self.evidence_hash


# ===========================================================================
# Detection
# ===========================================================================
class DetectionResult(DomainModel):
    """Output of the cybersecurity detection pipeline."""

    detector_name: str
    detector_kind: DetectorKind
    model_version: str = "unversioned"
    timestamp: datetime
    device_id: str | None = None
    is_attack: bool = False
    attack_type: AttackType = AttackType.NONE
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    anomaly_score: float | None = Field(default=None, description="Higher = more anomalous")
    severity: Severity = Severity.INFO
    # Per-class scores where the detector supports them.
    class_scores: dict[str, float] = Field(default_factory=dict)
    contributing_features: dict[str, float] = Field(default_factory=dict)
    window_start: datetime | None = None
    window_end: datetime | None = None
    evidence_event_ids: list[str] = Field(default_factory=list)
    assertion_class: AssertionClass = AssertionClass.INFERENCE
    notes: str = ""


# ===========================================================================
# Risk
# ===========================================================================
class RiskFactor(DomainModel):
    """One explained contribution to a risk score."""

    name: str
    value: float
    weight: float
    contribution: float
    rationale: str = ""
    assertion_class: AssertionClass = AssertionClass.OBSERVED_FACT


def _band(score: float) -> RiskBand:
    if score < 0.15:
        return RiskBand.NEGLIGIBLE
    if score < 0.35:
        return RiskBand.LOW
    if score < 0.60:
        return RiskBand.MODERATE
    if score < 0.82:
        return RiskBand.HIGH
    return RiskBand.SEVERE


class CyberRiskResult(DomainModel):
    score: float = Field(ge=0.0, le=1.0)
    factors: list[RiskFactor] = Field(default_factory=list)
    uncertainty: float = Field(default=0.0, ge=0.0, le=1.0)
    explanation: str = ""
    formulation_version: str = "v1"

    @computed_field  # type: ignore[prop-decorator]
    @property
    def band(self) -> RiskBand:
        return _band(self.score)


class ClinicalRiskResult(DomainModel):
    score: float = Field(ge=0.0, le=1.0)
    factors: list[RiskFactor] = Field(default_factory=list)
    uncertainty: float = Field(default=0.0, ge=0.0, le=1.0)
    explanation: str = ""
    formulation_version: str = "v1"
    # Surfaced separately because the policy engine hard-gates on these.
    life_support_involved: bool = False
    patient_dependency: PatientDependencyLevel = PatientDependencyLevel.NONE

    @computed_field  # type: ignore[prop-decorator]
    @property
    def band(self) -> RiskBand:
        return _band(self.score)


class ResponseImpactResult(DomainModel):
    """Impact assessment of ONE candidate response action."""

    action_type: ResponseActionType
    security_benefit: float = Field(ge=0.0, le=1.0)
    clinical_impact: float = Field(ge=0.0, le=1.0)
    service_interruption_seconds: float = Field(default=0.0, ge=0.0)
    reversible: bool = True
    backup_available: bool = False
    impact_class: ImpactClass = ImpactClass.LOW
    factors: list[RiskFactor] = Field(default_factory=list)
    explanation: str = ""
    formulation_version: str = "v1"

    @computed_field  # type: ignore[prop-decorator]
    @property
    def net_benefit(self) -> float:
        """Security gained minus clinical cost. Diagnostic, not the decision."""
        return round(self.security_benefit - self.clinical_impact, 6)


class PatientAwareDecision(DomainModel):
    """The central research artefact: the dual-risk decision record.

    This object is what makes the contribution auditable. It records the
    cyber risk, the clinical risk, the impact of every candidate considered,
    the chosen action, the deterministic rationale, and the counterfactual
    (what a cyber-risk-only defender would have chosen) so the trade-off is
    measurable rather than asserted.
    """

    incident_id: str
    decided_at: datetime
    cyber_risk: CyberRiskResult
    clinical_risk: ClinicalRiskResult
    candidate_impacts: list[ResponseImpactResult] = Field(default_factory=list)
    selected_action: ResponseActionType = ResponseActionType.MONITOR_ONLY
    decision_score: float = Field(default=0.0, description="Score of the selected candidate")
    decision_band: RiskBand = RiskBand.LOW
    rationale: str = ""
    # Counterfactual: the action a security-only policy would have taken.
    cyber_only_action: ResponseActionType | None = None
    diverged_from_cyber_only: bool = False
    divergence_reason: str = ""
    formulation_version: str = "v1"
    engine: Literal["deterministic"] = "deterministic"
    assertion_class: AssertionClass = AssertionClass.RECOMMENDATION


# ===========================================================================
# Agentic layer
# ===========================================================================
class ToolCallRecord(DomainModel):
    """Audit record of one agent tool invocation."""

    tool_call_id: str
    agent_role: AgentRole
    tool_name: str
    arguments: dict[str, Any] = Field(default_factory=dict)
    succeeded: bool = True
    error: str | None = None
    duration_ms: float = 0.0
    result_digest: str | None = None
    authority_violation: bool = False


class AgentFinding(DomainModel):
    """A single structured, epistemically-tagged agent statement."""

    statement: str
    assertion_class: AssertionClass
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    supporting_evidence_ids: list[str] = Field(default_factory=list)


class AgentRunRecord(DomainModel):
    """Full audit record of one agent execution."""

    agent_run_id: str
    incident_id: str
    agent_role: AgentRole
    status: AgentRunStatus = AgentRunStatus.PENDING
    started_at: datetime
    finished_at: datetime | None = None
    provider: str = "deterministic"
    model: str = "deterministic"
    attempts: int = 1
    tool_calls: list[ToolCallRecord] = Field(default_factory=list)
    findings: list[AgentFinding] = Field(default_factory=list)
    structured_output: dict[str, Any] = Field(default_factory=dict)
    validation_errors: list[str] = Field(default_factory=list)
    error: str | None = None

    @computed_field  # type: ignore[prop-decorator]
    @property
    def duration_ms(self) -> float:
        if self.finished_at is None:
            return 0.0
        return (self.finished_at - self.started_at).total_seconds() * 1000.0

    @computed_field  # type: ignore[prop-decorator]
    @property
    def tool_success_rate(self) -> float:
        if not self.tool_calls:
            return 1.0
        return sum(1 for c in self.tool_calls if c.succeeded) / len(self.tool_calls)


# ===========================================================================
# Response, policy, approval, recovery
# ===========================================================================
class ResponseCandidate(DomainModel):
    """A proposed response action before policy evaluation."""

    action_type: ResponseActionType
    target_device_id: str | None = None
    target_segment: str | None = None
    target_source_ip: str | None = None
    parameters: dict[str, Any] = Field(default_factory=dict)
    proposed_by: str = "response_planning_agent"
    expected_security_benefit: float = Field(default=0.0, ge=0.0, le=1.0)
    rationale: str = ""
    assertion_class: AssertionClass = AssertionClass.RECOMMENDATION


class PolicyEvaluation(DomainModel):
    """Deterministic policy verdict on one candidate. Authoritative."""

    action_type: ResponseActionType
    decision: PolicyDecision
    impact_class: ImpactClass
    matched_rule: str = ""
    reasons: list[str] = Field(default_factory=list)
    required_role: str | None = None
    policy_version: str = "v1"
    assertion_class: AssertionClass = AssertionClass.OBSERVED_FACT


class ApprovalRecord(DomainModel):
    approval_id: str
    incident_id: str
    response_id: str
    status: ApprovalStatus = ApprovalStatus.PENDING
    requested_at: datetime
    required_role: str = "clinical_approver"
    decided_at: datetime | None = None
    approver: str | None = None
    justification: str = ""
    expires_at: datetime | None = None


class ResponseRecord(DomainModel):
    """Lifecycle record of one response through the state machine."""

    response_id: str
    incident_id: str
    candidate: ResponseCandidate
    state: ResponseState = ResponseState.PROPOSED
    policy: PolicyEvaluation | None = None
    impact: ResponseImpactResult | None = None
    approval: ApprovalRecord | None = None
    proposed_at: datetime
    executed_at: datetime | None = None
    execution_succeeded: bool | None = None
    execution_detail: str = ""
    side_effects: list[str] = Field(default_factory=list)
    transitions: list[dict[str, Any]] = Field(default_factory=list)
    attempt_number: int = 1


class RecoveryCheck(DomainModel):
    name: str
    passed: bool
    observed: str = ""
    expected: str = ""
    assertion_class: AssertionClass = AssertionClass.OBSERVED_FACT


class RecoveryResult(DomainModel):
    recovery_id: str
    incident_id: str
    response_id: str
    verified_at: datetime
    outcome: RecoveryOutcome
    checks: list[RecoveryCheck] = Field(default_factory=list)
    residual_risk: float = Field(default=0.0, ge=0.0, le=1.0)
    residual_factors: list[RiskFactor] = Field(default_factory=list)
    requires_reinvestigation: bool = False
    explanation: str = ""
    # Actions already tried, so re-planning cannot blindly repeat them.
    exhausted_actions: list[ResponseActionType] = Field(default_factory=list)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def checks_passed(self) -> int:
        return sum(1 for c in self.checks if c.passed)


# ===========================================================================
# Provenance
# ===========================================================================
class ProvenanceRecord(DomainModel):
    """A record committed to the permissioned ledger.

    Deliberately small: identifiers, hashes, verdicts and timestamps only.
    Raw telemetry, logs, synthetic patient context and model artefacts stay
    off-chain and are referenced by hash.
    """

    provenance_id: str
    event_type: ProvenanceEventType
    incident_id: str
    device_id: str | None = None
    timestamp: datetime
    evidence_hash: str = ""
    detector_result_hash: str | None = None
    risk_summary: dict[str, float] = Field(default_factory=dict)
    agent_decision: str | None = None
    recommended_action: str | None = None
    approval_status: str | None = None
    approver: str | None = None
    executed_action: str | None = None
    execution_result: str | None = None
    recovery_result: str | None = None
    policy_version: str | None = None
    formulation_version: str | None = None
    submitting_org: str = "SecurityOpsMSP"

    def payload_for_ledger(self) -> dict[str, Any]:
        """Canonical, minimal dict actually written to the ledger."""
        data = self.model_dump(mode="json", exclude_none=True)
        for forbidden in ("payload", "patient", "telemetry"):
            data.pop(forbidden, None)
        return data


class LedgerReceipt(DomainModel):
    """Proof that a provenance record was committed."""

    provenance_id: str
    backend: str
    transaction_id: str
    block_number: int | None = None
    committed_at: datetime
    record_hash: str
    previous_hash: str | None = None
    latency_ms: float = 0.0


# ===========================================================================
# Incident
# ===========================================================================
class IncidentTimelineEntry(DomainModel):
    timestamp: datetime
    actor: str
    phase: str
    message: str
    assertion_class: AssertionClass = AssertionClass.OBSERVED_FACT
    data: dict[str, Any] = Field(default_factory=dict)


class Incident(DomainModel):
    """The aggregate the whole closed loop revolves around."""

    incident_id: str
    created_at: datetime
    updated_at: datetime
    state: IncidentState = IncidentState.DETECTED
    device_id: str | None = None
    attack_type: AttackType = AttackType.UNKNOWN
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    severity: Severity = Severity.INFO
    detection: DetectionResult | None = None
    evidence: list[EvidenceRef] = Field(default_factory=list)
    timeline: list[IncidentTimelineEntry] = Field(default_factory=list)
    agent_runs: list[AgentRunRecord] = Field(default_factory=list)
    cyber_risk: CyberRiskResult | None = None
    clinical_risk: ClinicalRiskResult | None = None
    decision: PatientAwareDecision | None = None
    responses: list[ResponseRecord] = Field(default_factory=list)
    recoveries: list[RecoveryResult] = Field(default_factory=list)
    provenance_refs: list[LedgerReceipt] = Field(default_factory=list)
    reinvestigation_count: int = 0
    scenario_id: str | None = None
    resolved_at: datetime | None = None
    # Metrics captured for the resilience evaluation (MTTD / MTTR).
    attack_started_at: datetime | None = None
    detected_at: datetime | None = None

    @computed_field  # type: ignore[prop-decorator]
    @property
    def approval_status(self) -> ApprovalStatus:
        for r in reversed(self.responses):
            if r.approval is not None:
                return r.approval.status
        return ApprovalStatus.NOT_REQUIRED

    @computed_field  # type: ignore[prop-decorator]
    @property
    def latest_response(self) -> ResponseRecord | None:
        return self.responses[-1] if self.responses else None

    @computed_field  # type: ignore[prop-decorator]
    @property
    def latest_recovery(self) -> RecoveryResult | None:
        return self.recoveries[-1] if self.recoveries else None

    @computed_field  # type: ignore[prop-decorator]
    @property
    def detection_latency_seconds(self) -> float | None:
        if self.attack_started_at is None or self.detected_at is None:
            return None
        return (self.detected_at - self.attack_started_at).total_seconds()

    @computed_field  # type: ignore[prop-decorator]
    @property
    def time_to_resolution_seconds(self) -> float | None:
        if self.detected_at is None or self.resolved_at is None:
            return None
        return (self.resolved_at - self.detected_at).total_seconds()

    def evidence_bundle_hash(self) -> str:
        """Aggregate hash over all evidence, committed at incident creation."""
        return canonical_hash(sorted(e.evidence_hash for e in self.evidence))


class IncidentContextPackage(DomainModel):
    """Read-only structured context handed to agents.

    Agents receive this rather than raw database access, which is how the
    tool authority boundary is enforced at the data layer too.
    """

    incident: Incident
    device_profile: DeviceProfile | None = None
    device_state: DeviceState | None = None
    recent_events: list[NormalisedEvent] = Field(default_factory=list)
    exhausted_actions: list[ResponseActionType] = Field(default_factory=list)


__all__ = [
    "AgentFinding",
    "AgentRunRecord",
    "ApprovalRecord",
    "ClinicalRiskResult",
    "CyberRiskResult",
    "DetectionResult",
    "DeviceProfile",
    "DeviceState",
    "DomainModel",
    "EvidenceRef",
    "Incident",
    "IncidentContextPackage",
    "IncidentTimelineEntry",
    "LedgerReceipt",
    "NormalisedEvent",
    "PatientAwareDecision",
    "PolicyEvaluation",
    "ProvenanceRecord",
    "RecoveryCheck",
    "RecoveryResult",
    "ResponseCandidate",
    "ResponseImpactResult",
    "ResponseRecord",
    "RiskFactor",
    "SyntheticPatientContext",
    "ToolCallRecord",
]
